name: Package and sign

on: [push]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write

    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.34

      # We are using Github's official attest action to create a sigstore certificate with
      # the Conda predicate.
      - uses: actions/attest@v1
        id: attest
        with:
          subject-path: "**/*.conda"
          predicate-type: "https://schemas.conda.org/attestations-publish-1.schema.json"
          predicate: "{\"targetChannel\": \"https://prefix.dev/sigstore-example\"}"

      # Note: no API keys needed because we have configured a trusted publisher!
      - name: Upload the package
        run: |
          rattler-build upload prefix -c sigstore-example ./output/**/*.conda --attestation ${{ steps.attest.outputs.bundle-path }}
